## Assignment 14-08-2020

**1.create an array with the values from 0 .. 23. And Check its attributes.
Then Reshape it as (2* 12),(3* 8), (4* 6),; (2* 2* 6), (2* 4* 3),(3* 4* 2),.... and check its attributes.**


In [24]:
import numpy as np
a = np.arange(24).reshape(2,12)
print(a)
print(type(a))
print(a.ndim)
print (a.size)
print (a.shape)
print(a.dtype)
print(a.itemsize)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
<class 'numpy.ndarray'>
2
24
(2, 12)
int32
4


In [28]:
b = a.reshape(3,8)
print(type(b))
print(b.ndim)
print (b.size)
print (b.shape)
print(b.dtype)
print(b.itemsize)

<class 'numpy.ndarray'>
2
24
(3, 8)
int32
4


In [29]:
c= a.reshape(4,6)
print(c)
print(type(c))
print(c.ndim)
print (c.size)
print (c.shape)
print(c.dtype)
print(c.itemsize)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
<class 'numpy.ndarray'>
2
24
(4, 6)
int32
4


In [31]:
d = a.reshape(2,2,6)
print(d)
print(type(d))
print(d.ndim)
print(d.size)
print(d.shape)
print(d.itemsize)
print(d.dtype)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]
<class 'numpy.ndarray'>
3
24
(2, 2, 6)
4
int32


In [50]:
e = a.reshape(2,4,3)
print(e)
print(type(e))
print(e.shape)
print(e.size)
print(e.ndim)
print(e.dtype)
print(e.itemsize)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
<class 'numpy.ndarray'>
(2, 4, 3)
24
3
int32
4


In [33]:
f =a.reshape(3,4,2)
print(f)
print(type(f))
print(f.size)
print(f.shape)
print(f.ndim)
print(f.dtype)
print(f.itemsize)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
<class 'numpy.ndarray'>
24
(3, 4, 2)
3
int32
4


**2.Apply a user defined function using vectorize to get the maximum of two arrays
Example : Array1 =  [5,7,9,8,6,4,5]
	     Array2 = [6,3,4,8,9,7,1]
     Output : [6,7,9,8,9,7,5]**


In [33]:
def compare(x,y):
    return min(x,y)
arr1 = [5,7,9,8,6,4,5]
arr2 = [6,3,4,8,9,7,1]
c = np.vectorize(compare)
c(arr1,arr2)

array([5, 3, 4, 8, 6, 4, 1])

**3.Write a Numpy program to generate six random integers between 10 and 30**

In [71]:
np.random.randint(10,30,6)

array([29, 15, 19, 26, 10, 15])

**4.Get all the items between 5 and 10 from Array A.
A = np.array([2,6,1,9,10,3,27])**


In [35]:
import numpy as np
a = np.array([2,6,1,9,10,27])
c = (a > 5) & (a <10)
print(a[c])


[6 9]


**5.Extract all odd numbers from the array.**

In [22]:
a = np.array([2,6,1,9,10,3,27])
b = (a%2 != 0)
a[b]

array([ 1,  9,  3, 27])