## Numpy

## Array : 
**grid of values of same type**

In [1]:
#creating array
list1= [1,2,4,5,7,4]
type(list1)

list

In [4]:
import numpy as np
arr1 = np.array(list1)#(start:stop)
print(arr1)
type(arr1)

[1 2 4 5 7 4]


numpy.ndarray

In [8]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr2 = np.arange(start =10, stop = 20, step = 1)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
print(arr2.ndim) # gives dimensions
print(arr2)

1
[10 11 12 13 14 15 16 17 18 19]


In [18]:
#creating 2D array
arr2 = arr2.reshape(5,2) # rows = 5 and columns = 2
arr2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape # no. of rows and colums

(5, 2)

In [21]:
arr2.size # no. of elements in array

10

In [25]:
arr2.dtype # data type of elements

dtype('int32')

In [24]:
arr2.itemsize # size of each element in bytes

4

In [26]:
a = 10
type(a)

int

In [38]:
# indexing
print (arr2)
arr2[4,0] # row index and column index starting from 0

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


18

In [39]:
arr2[3] # extracting entire row

array([16, 17])

In [41]:
# extract top 3 rows
arr2[:3]

array([[10, 11],
       [12, 13],
       [14, 15]])

In [43]:
arr2[:,1] # all the row elements of 2nd column

array([11, 13, 15, 17, 19])

In [45]:
arr2[2:4,0]# extract 3and 4 rows of 0th column

array([14, 16])

In [47]:
a =np.linspace(1,10) # include elements from 1 -10 default no. of elements = 20
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [55]:
a = np.linspace(1, 10, 19) # (start, stop, number of elements)
a

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [58]:
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
#Convert 2D array to 1D
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [62]:
print(b)
print(b.min())
print(b.max())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
0
19


In [68]:
print(arr2)
print(arr2.min())
print(arr2.argmin()) # index of min value

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
10
0


In [69]:
print(arr2.max())
print(arr2.argmax())

19
9


In [71]:
arr2.sum() #returns sum of all the elements

145

In [72]:
np.sqrt(arr2) # sqare root of every element

array([[3.16227766, 3.31662479],
       [3.46410162, 3.60555128],
       [3.74165739, 3.87298335],
       [4.        , 4.12310563],
       [4.24264069, 4.35889894]])

In [2]:
import numpy as np
ar1 = np.arange(1,10).reshape(3,3)
ar2 = np.arange(11,20).reshape(3,3)
print (ar1)
print (ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [3]:
np.hstack([ar1,ar2]) # stacking arrays horizontaly

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [4]:
np.vstack ([ar1,ar2])# stacking arrays verticaly

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [7]:
a= np.arange (8).reshape(2,4)
b = np.arange(2).reshape(2,1)
print (a)
print(b)

[[0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]]


In [8]:
np.hstack([a,b]) # hstack needs rows to be equal while vstack needs equal columns in arrays

array([[0, 1, 2, 3, 0],
       [4, 5, 6, 7, 1]])

## Applying User defined functions

In [10]:
def calculate(x):
    return x*x-5

In [11]:
cal = np.vectorize(calculate)# vectorize means calling user defined function
cal([1,2,3,4,5])

array([-4, -1,  4, 11, 20])

In [24]:
#random functions
from numpy import random
a = random.rand()
#a.round()
print(random.rand())
print(random.randint(0,6))
print(random.seed())



0.08960271179442203
1
None


In [26]:
r = np.random.RandomState(1) # gives single value even after generating multiple times
a = r.rand()
print(a)
print(np.round(a,decimals=2))

0.417022004702574
0.42


In [29]:
arr = random.randint(100, size=(2,3))# elemts below 100 and aray size 2*3
arr

array([[93, 11, 81],
       [80,  0, 86]])

In [30]:
random.choice(arr)

ValueError: a must be 1-dimensional

In [31]:
random.choice(arr.ravel()) # pick a random number from a 1 D array, ravel converts to 1D array

80

In [32]:
random.choice([1,2,3,5,6], size=(2,3))

array([[6, 2, 2],
       [3, 2, 5]])

In [35]:
# using random.seed() will not replace with new random numbers in the next line.
#Now it gives same matrix even after multple iterations
random.seed(5)
random.choice([1,2,3,5,6], size=(2,3))

array([[5, 1, 2],
       [1, 6, 5]])